import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "homework TTsolution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-8 bg-gray-100">
        {children}
      </body>
    </html>
  );
}
